### ISSUE TITLE
separate local template directory operations from github operations

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#104]
The assignment-template script (see PR #91) does two things: 1. Create a local directory with assignment files and initializes it as a git repo; and 2. Creates a remote github repository and pushes the local repo to github. It would be better to separate these into two different console scripts (and then allow the options to refresh the local / remote repo after changes).

**Comment by lwasser** [comment]
this relates to the discussion here: #105 which i think we should just think through!!

**Comment by kcranston** [comment]
I think we can close this now that #121 is merged

**Comment by lwasser** [comment]
awesome. thanks @kcranston Maybe we can do a quick issue close sess when we chat todya too!!
