### ISSUE TITLE
Create new template creates gitignore not .gitignore

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#106]
hey @kcranston when the abc-template command is run, it creates a readme and a gitignore. however the gitignore is missing a `.` so i don't think it will be processed properly by git. 

we will need to fix this.

**Comment by kcranston** [comment]
I think this is an error in the `sample_config.py`. See [line 49](https://github.com/earthlab/abc-classroom/blob/master/sample_config.yml#L49).

Easy fix!

**Comment by lwasser** [comment]
totally - did you try it @kcranston ? when i tried it on friday it still created `gitignore` without the period.

**Comment by kcranston** [comment]
Hmmm... I hope this isn't some strange operating system / environment difference. Here is the relevent part of my config:

```
# Additional files that will be created and added to the student repositories
# Each item in the list will be added as a line in the file
extra_files:
  .gitignore:
  - .ipynb_checkpoints
  - .DS_Store
```

and when I run `abc-assignment-template testing123 --local-only --mode delete`, and then look in the directory:

```
test-new-abc-classroom  ls -a assignment_repos/ea-testing123-template
.               .git            README.md       homework2.ipynb
..              .gitignore      homework1.ipynb
```

**Comment by lwasser** [comment]
ok i'll try again tomorrow @kcranston !! perhaps i need to start fresh.

**Comment by lwasser** [comment]
ok i did another test and it does seem to work via the config edit!! i will close this!!
