### ISSUE TITLE
print relative, not absolute paths in stdout

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#107]
In the abc-assignment-template methods, we print full absolute paths in stdout, and it would be cleaner to simply print relative paths, for example:

current output: 

`Directory /Users/karen/Documents/earthlab/test_courses/test-new-abc-classroom/assignment_repos/ea-testing123-template already exists; re-run with '--mode merge' or --mode delete', or delete / move directory before re-running`

cleaner output (from the test-new-abc-classroom dir): 

`Directory assignment_repos/ea-testing123-template already exists; re-run with '--mode merge' or --mode delete', or delete / move directory before re-running`

**Comment by lwasser** [comment]
this also is a very old issue... pinging you again @kcranston maybe we can close some of these very old issues if they have'nt been persistent?

**Comment by lwasser** [comment]
this is more aesthetic than function so we will close for now but another maintainer could re-open in the future if it makes sense.
