### ISSUE TITLE
Error messages when running `pip install -e .`

### ISSUE THREAD

**Issue by Ram-N** [earthlab/abc-classroom#112]
Was trying to get my dev env set up. I followed the instructions in the `Contributing` file. (Windows 10 machine)

When I ran `pip install -e .` it did successfully build the required packages, but I got the following errors. Perhaps because they are dependencies of other dependencies.
```
Successfully built future nbgrader pandocfilters pyrsistent sqlalchemy alembic prometheus-client Mako pycparser backcall
ERROR: twine 2.0.0 requires pkginfo>=1.4.2, which is not installed.
ERROR: readme-renderer 24.0 requires docutils>=0.13.1, which is not installed.
```

`pip install` did complete, but reporting it here for completeness.

**Comment by lwasser** [comment]
hey @Ram-N !! welcome and thank you for this issue!! we will have a look at it. i'm curious if @nkorinek who is also on windows ran into something similar. i can test it on a windows vm later this week as well :)

**Comment by nkorinek** [comment]
@Ram-N @lwasser Hey all! I uninstalled everything on my computer and did a fresh install of abc-classroom and the dev environment, and I couldn't get this to reproduce. Sadly I haven't seen that error before!

**Comment by lwasser** [comment]
i haven't been able to reproduce it either on my end. @Ram-N is this still an issue? can you run conda info if it is and provide the outputs here. and then conda list.

**Comment by lwasser** [comment]
ok i will close this since it's been stale for a few weeks. IF we need to reopen, please say the word!!
