### ISSUE TITLE
Sphinx generated ReadtheDocs pages are not rendering properly

### ISSUE THREAD

**Issue by Ram-N** [earthlab/abc-classroom#113]
Hi all,

As it now stands, https://abc-classroom.readthedocs.io/en/latest/ is not rendering several of the rst pages correctly.  (In fact, this is what prompted me to ask Leah for additional documentation.) But after cloning the repo, I realize that these pages do exist, they are just not rendering in the current `readthedocs` build. Also, the [module index](https://abc-classroom.readthedocs.io/en/latest/py-modindex.html) page is throwing a 404.

After a bit of tinkering, I have managed to render all the Documentation pages, including the Module index correctly on my *local* `_build/html`

This involved a few changes to docs/conf.py, and index.rst. (Also, I had to eliminate `api.rst` because the documents simply don't render with it present.)

@lwasser Please let me know if there is interest, and I am happy to issue a PR with these (documentation-only) changes.

**Comment by lwasser** [comment]
@Ram-N  pr's are totally welcome!! please go ahead and submit one. THANK YOU SO MUCH!!! this project is very new and i'm sure it's full of bugs. your help is very welcome!!!

**Comment by lwasser** [comment]
@Ram-N just a note that i just checked the RTD config and noticed some problems on that end. the docs are building locally for me BUT... let me test this out

https://github.com/earthlab/abc-classroom/pull/115

first just to see if config updates help... and then you can tell me specifically what was not working. the api.rst files i think require the m2r module which wasn't being installed in RTD... i'll followup here after i see how RTD builds (or doesn't build) things in my new pr!!

**Comment by lwasser** [comment]
@Ram-N thank you again for noticing this
Please have a look at the docs. they seem to be building for me now - there were several config issues in RTD that i had to clean up and the API part... that had to do with a missing dependency and files in github needed to build the api reference. 

https://abc-classroom.readthedocs.io/en/latest/ 

let me know if this looks good to you now!!

**Comment by Ram-N** [comment]
@lwasser the docs are definitely better. However, I am still seeing some issues.
For one concrete example, when I click on Index, I am getting a blank page.
In my local build, index is full of references. (See Screen shot below):
![image](https://user-images.githubusercontent.com/737241/67430566-7fe0d100-f5b0-11e9-8710-36a7b998e9de.png)

Also, there is still a lot more links that I see in my local build of index.html compared to the "production" version in https://abc-classroom.readthedocs.io/en/latest/

Two screenshots follow: What I see in production vs. what I am seeing in my local build:
![image](https://user-images.githubusercontent.com/737241/67430655-b28ac980-f5b0-11e9-9b96-aeb3b23d0986.png)

In my local build, the RTD index.html is much more verbose:
![image](https://user-images.githubusercontent.com/737241/67430720-d8b06980-f5b0-11e9-8128-6fa3ba271743.png)

**Comment by lwasser** [comment]
hi @Ram-N i believe that these issues have been addressed! when i look at the [index page](https://abc-classroom.readthedocs.io/en/latest/genindex.html) i see a full page and the [table of contents](https://abc-classroom.readthedocs.io/en/latest/index.html) is also fully fleshed out. please have a look but everything seems to be building now as far as i can see. i'm wondering if the page was cached for you perhaps??

**Comment by lwasser** [comment]
Given this has been stale for a while, i am closing this BUT if anything comes up let's reopen it!
