### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#12]
This package needs a better name, especially as it grows up and starts being useful instead of a collection of experiments.

My current proposal: "teaching and learning with notebooks" shortened to `tln` (or `tlnb`). Commands would become `tln-distribute` and `tln-author` instead of `nbdistribute` and `nbauthor`.

It is descriptive, can be shortened to a TLA (three letter acronym) and for vanity contains the initials of Tim and Leah 😂

**Comment by mbjoseph** [comment]
I will throw `nbteach` over the wall, with commands `nbteach-distribute` & `nbteach-author` :man_shrugging:

**Comment by lwasser** [comment]
gonna think about this a bit more! i like removing the nb part as it doesn't seen required. 
words
* autograde
* class
* class_grades # Pep8 likes underscores right unless it's ClassesWhereItWantsCamelCase 
* gc, grade class
* auto_classroom
* auto_learn  <- @betatim can you make this function for my brain so i get better at coding??
* abc auto-build-classroom # maybe this is a repo name where we want dashes  ABC!! singing the jackson 5 now....

This package really sets up an entire classroom development workflow so it's more than teaching and more than grading. it's pretty sweet.

**Comment by betatim** [comment]
We decided on `abc` on slack.

I asked if we could get control over the ABC name on pypi.org [here](https://github.com/pypa/warehouse/issues/5212). Let's see what happens.

**Comment by betatim** [comment]
Settled on `abc-classroom` for now.
