### ISSUE TITLE
Does the nbgrader_dir yaml element need to be called nbgrader?

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#133]
I finally realized we don't need this name. We just need a directory name for assignments so that name could be assignments or in this case assignments/release if using nbgrader. 

@kcranston is there ANY reason why we can't just adjust this to find an assignment directory? by default we can call is assignments. **if** someone is using nbgrader they would specify nbgrader/release as the location. 

this might be the best way to move forward without a need for nbgrader.

**Comment by lwasser** [comment]
in followup to this -- the abc-quickstart could create an assignments directory by default as well. 
Does anyone know if nbgrader can be configured to take a different assignment directory structure? if not we can just have that nbgrader_dir yaml element and rename it to 

assignment_location: 

Then if they use nbgrader it might have a path like `nbgrader/release` otherwise it is empty and looks for the assignment directory.

**Comment by kcranston** [comment]
Good question! There is no reason to call this the `nbgrader` dir in the config. The tricky bit is that if you are using nbgrader, we expect to find the whole directory structure, e.g. 

```
nbgrader_coursename
   source
   release
   submitted
   autograded
   feedback
```

So, for someone _not_ using nbgrader, would we assume the same directory structure, or would they need to specify the location of files at each stage of the grading workflow?

**Comment by kcranston** [comment]
Thinking about this is a different way... if someone isn't using nbgrader, what is the workflow for abc-classroom:

* create material and put it in a 'release' directory
* create template repos from the 'release directory (pushes content to students via github)
* pull completed student assignments from github into a 'submitted' directory
* grade the assignments and put output in a 'feedback' directory
* push feedback to students

**Comment by lwasser** [comment]
let's make this yaml element a more generic name! 

`course_materials` perhaps??

**Comment by kcranston** [comment]
Done - now called course_materials in the config and also throughout the code and docs.
