### ISSUE TITLE
How to use assignment names with abc-classroom

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#137]
i think that right now you run

`abc-update-template ps1` to build a template repo associated with an assignment named `ps1` which is the default nbgrader assignment name. 

However, once you get to closing, the template repo may have more text appended to it like `ea-ps1`. The clone functionality currently proposed #126 requires the full name of the assignment which it think is then `ea-ps1` rather than `ps1`. This is confusing to a user as there are then "two" assignment names. It would be ideal if the same assignment name is used throughout

**Comment by kcranston** [comment]
I agree that this is confusing. We want abc-classroom to be helpful, but not too helpful. :)

The assignment name in abc-classroom must match the assignment name in nbgrader and in github classroom. So, it is going to be confusing if abc-classroom changes the assignment name by appending extra text. Let's just take what the user provides without modification, and maybe include a tip in the docs about pre-pending a course identifier to the assignment name?

**Comment by lwasser** [comment]
@kcranston i like this solution. it's the cleanest and simplest!! thank you.
