### ISSUE TITLE
Can abc classroom help us track assignments by creating a yaml list in the config file?

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#138]
I know nbgrader does this... but i'm getting confused by assignments and names and such.

just wondering if it could append to the config file each time an assignment is created.

It also would be ideal if somehow abc-classroom could keep track of the assignments setup within the classroom. Because it's easy to forget each assignment name. IF the github classroom api is built out this may be possible using that. but for now, could we develop something simple even if it's a yaml list to track assignments and repos and such in one place? 

Implementation something like this (just the most basic thing to keep track of each template and assignment:
```
assignments
   - assignment-1
   - template repo: ea-assignment-1-template 
```

**Comment by kcranston** [comment]
PR #141 added this functionality. Note that it only adds new assignments (it doesn't know when you delete one).

**Comment by lwasser** [comment]
just a note that it is doing a few unexpected things ... see here #161 but we can chat today about it too!!
