### ISSUE TITLE
Autograding big picture notes 

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#154]
Please note the list below is just an ongoing list of things that would be cool to do. Some relate to changes for matplotcheck.

1.  ag.run_test: can we allow the test to provide it's own output?? right now we are providing a . message which is written / rendered in the output of the notebook. 

2. Work on making this easier to read. can jupyter output colored text or bold, etc? and if not we can get creative with how things are written. Right now pass vs fail look super similar. maybe we could use emojis or something to output checks and x's??  oh yes -- this is what we need: 

https://medium.com/@sawanrai777/have-fun-with-emojis-in-jupyter-notebook-f74db7f45210 i will play with it a bit!! 

<img width="792" alt="Screen Shot 2020-01-13 at 8 30 20 PM" src="https://user-images.githubusercontent.com/7649194/72311928-9e041d80-3643-11ea-89a7-c784b5eeee47.png">

***
- [ ] Nbgrader -- i got a very obsscure error. the issue is the number of points in the cell don't add up to the cell value. but the error wasn't helpful in telling me that was the issue.  

<img width="692" alt="Screen Shot 2020-01-14 at 2 35 21 PM" src="https://user-images.githubusercontent.com/7649194/72384686-34cfe900-36db-11ea-9881-9d1fcb553fac.png">

***
It looks like when i have cells with tests, it creates empty cells. I would think it would remove those cells. 
<img width="1146" alt="Screen Shot 2020-01-14 at 2 44 52 PM" src="https://user-images.githubusercontent.com/7649194/72385312-73b26e80-36dc-11ea-9a1b-13e2007d15bb.png">

***
not sure why but i'm running into path issues
<img width="1112" alt="Screen Shot 2020-01-14 at 3 03 11 PM" src="https://user-images.githubusercontent.com/7649194/72386656-03591c80-36df-11ea-8209-52c35c69833f.png">

**Comment by lwasser** [comment]
actually i think it's trying to grab the check points or something to create the template repo??

**Comment by kcranston** [comment]
Ah, that last one is interesting. We are currently trying to copy everything from the course materials folder to the template (this is a change from previous behaviour where we copied only *.ipynb files). Here are some options for fixing this - we could use one or more of these:

* copy only items that do not start with `.`
* copy only files, not directories (we would therefore assume that any required files were not in subfolders)
* copy only files that match a specific patterns, i.e. *.ipynb, *.jpg, etc (this could be set in the config)
* simply give a warning for things that are not copied, not an error

**Comment by lwasser** [comment]
closing this as we aren't handling autograding in the scope of this repo and we already handled file transfer issues separately.
