### ISSUE TITLE
configure codacy to suppress assert errors

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#158]
One of the Codacy checks is the [bandit](https://pypi.org/project/bandit/) security linter, and one of its defaults is to flag assert statements. This causes Codacy to complain about every assert statement in pytest files. 

To fix, add a bandit.yml file that suppresses these errors, as explained on the [Codacy code patterns](https://support.codacy.com/hc/en-us/articles/207994335-Code-Patterns) - search this page for 'assert'. PR coming shortly.

**Comment by lwasser** [comment]
hey @kcranston i just turned off codacy as all of the pr's are failing. what do you think about just removing it for the time being? everything is failing now because of it :)

**Comment by kcranston** [comment]
I am ambivalent. PR #159 removes all of the errors that are due to assert statements in tests. It did catch a few unused variables in one of my other PRs. We can either leave it off, or turn it back on once we merge 159 to see if the remaining errors are useful.

**Comment by lwasser** [comment]
ahhhh ok! it's easy to turn back on if it does catch some things.
