### ISSUE TITLE
quickstart quirks (i think?)

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#160]
When i run abc-quickstart -- it creates this structure

<img width="259" alt="Screen Shot 2020-01-23 at 12 23 06 PM" src="https://user-images.githubusercontent.com/7649194/73016510-35ebcf00-3ddb-11ea-8370-efc366c32db5.png">

When i run abc-new-template it creates another dir like this:

<img width="631" alt="Screen Shot 2020-01-23 at 12 25 21 PM" src="https://user-images.githubusercontent.com/7649194/73016623-777c7a00-3ddb-11ea-9e30-600628ebe89a.png">

I think assignment-template-repos is more expressive. the function should not create a separate `assignment_repos` dir.

**Comment by lwasser** [comment]
@kcranston is this leah-error or a quirk in the code? i haven't looked closely at the code yet.

**Comment by lwasser** [comment]
UPDATE: leah error: 
```
# Path to the assignment template repositories. Again, none of
# the parent directories should be a git repo. Assumed to be relative to
# course_dir unless you enter an absolute path (i.e. starting with '/' on
# Linux or OS X or with 'C:' on Windows).
template_dir: assignment-repos-template
```
Config setting. it's probably good to add this to the docs

**Comment by kcranston** [comment]
This is fixed in PR #157

**Comment by lwasser** [comment]
awesome!! ok thanks... i'll test it out locally :)

**Comment by kcranston** [comment]
There is still an issue here, because quickstart hard codes the directory names rather than pulling them from the example config. I'll update the code.
