### ISSUE TITLE
Running abc-init results in error (varying on abc-classroom install method)

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/abc-classroom#163]
If abc-classroom has been installed using ```pip install abc-classroom```, running ```abc-init``` results in a token NOT being generated on GitHub, and a generated error in CLI:
```
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-init", line 8, in <module>
    sys.exit(init())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 51, in init
    gh_auth = get_github_auth()
NameError: name 'get_github_auth' is not defined
```

If abc-classroom has been installed using ```pip install git+git://github.com/earthlab/abc-classroom```, running ```abc-init``` results in a token generated on GitHub, but a generated error in CLI:
```
Traceback (most recent call last):
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/bin/abc-init", line 8, in <module>
    sys.exit(init())
  File "/home/jpalomino/miniconda3/envs/earth-analytics-python/lib/python3.7/site-packages/abcclassroom/__main__.py", line 93, in init
    set_github_auth({"token": auth.token, "id": auth.id})
NameError: name 'set_github_auth' is not defined
```

In either case, ```.abc-classroom.tokens.yml``` is not created under the home directory.

**Comment by kcranston** [comment]
Both `get_github_auth` and `set_github_auth` are defined in config.py, which is imported on line 19 as `from . import config as cf`. So, the calls on lines 52 and 93 should be `cf.set_github_auth` and `cf.set_github_auth`. One of those got fixed _after_ version 0.0.12 on pip, which is why the two install methods differ. The other one needs to get fixed, and then we need to do a new release.

**Comment by kcranston** [comment]
This also falls in the category of 'needs tests that include mocking'.

**Comment by lwasser** [comment]
@kcranston what is the fix? i'm just curious. is it literally i see some calls are missing `cf.` ?? i will laugh at myself if that is the actual fix because i didn't notice that until just now. i'll do a new release too... goodness. thank you.

**Comment by lwasser** [comment]
<img width="760" alt="Screen Shot 2020-01-23 at 5 43 20 PM" src="https://user-images.githubusercontent.com/7649194/73036162-e40d6e00-3e07-11ea-9b0c-95be5eb95896.png">
just a note that codacy is actually catching this stuff. That does seem useful.
