### ISSUE TITLE
Canonical style for abc-classroom in the docs

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#165]
This is minor, but since I am starting some major docs work - what do we want as the canonical style when we refer to abc-classroom in the docs?

* abc-classroom
* _abc-classroom_
* `abc-classroom`

In the earthpy docs, we use italics (_EarthPy_ ) on the [index page](https://earthpy.readthedocs.io/en/latest/index.html) and plain text (EarthPy) everywhere else, e.g. [data set page](https://earthpy.readthedocs.io/en/latest/earthpy-data-subsets.html).

Also, I assuming capitalization is abc-classroom and not ABC-classroom.

**Comment by lwasser** [comment]
Definitely lower case!! I often look at other packages. It seems like italics or bold are good ideas? Rasterio does nothing. I like the idea of calling attention to the name  We never really discussed it. How about bold?

**Comment by kcranston** [comment]
I did lower case and bold in PR #166 

Easy to change later.
