### ISSUE TITLE
Set kernel name for notebooks with papermill

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#20]
Set the kernel name to just "Python" when running a notebook in papermill

**Comment by betatim** [comment]
What do you think of the option of cleaning the kernel name when we run `nbdistribute` @lwasser? I think that is my favourite option at the moment.

This means that either on the `nbauthor` or `nbdistribute` step we'd check what kernel name is in a notebook and if it is "something weird" we set it to python or R without the appendage you get from using sth like the conda environment manager extension (not sure what exactly it is called). This way instructors can keep their workflow and for students (and the grading bot) things are simple.

**Comment by lwasser** [comment]
Ahhhh this makes so much sense. I don't know why i never thought about launching atom from the CLI with the envt active. I get generally how it works. So many "nice features" to work around :) ha!
Well this sounds great. If a clean of the notebook will make life easier, let's do it. if that package becomes too cumbersome to our workflow please let me know and i'll dig into it more.
