### ISSUE TITLE
Check who accepted the course invitation

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#22]
Create a tool that an instructor can run to get an overview of which students have/don't have accepted the invitation to the course by checking if there is a repository for them

Started in https://github.com/earthlab/grading-workflow-experiments/issues/16#issuecomment-444385117

**Comment by lwasser** [comment]
nbdistribute goes through all of the student and fetches their work
it can detect that the students don't have a repo... good place to start
