### ISSUE TITLE
Prevent feedback reports from containing hidden tests

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#238]
We would like the feedback reports to contain output from hidden tests (success / failure messages for students) but not the tests themselves. This allows us to re-use tests across classes without the answers being readily available in feedback reports from previous classes. This is an open nbgrader issue, see https://github.com/jupyter/nbgrader/issues/917 and https://github.com/jupyter/nbgrader/issues/1156

Options suggested in these issues:

1. Change nbgrader functionality through a PR to nbgrader (possibly running `ClearHiddenTests` pre-processor during feedback generation)
1. Put hidden tests in a separate file and then import that file (this might also be a way to tackle things like linting that don't fit the nbgrader autograding model)
1. Write a post-processor for the feedback report to strip out the hidden tests (by modifying the html directly).

**Comment by lwasser** [comment]
this is an issue because we will have to nest the answers within the hidden tests. so it would expose all of the answers. And also it exposes tests that could be shared with students in the next year.
