### ISSUE TITLE
Spurious github3.py log messages

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#24]
Below an issue I might file with github3.py if I cna't work out why this is happening. Tim is seeing a whole bunch of `info` level log messages from github3.py which shouldn't appear.

---

There are two places ([here](https://github.com/sigmavirus24/github3.py/blob/70828846f97427dcc48c4a9fabd4b830360c8fc2/src/github3/models.py#L181) and [here](https://github.com/sigmavirus24/github3.py/blob/b8f81a0ff51d3c020e78eaa35ae38995a56d9818/src/github3/session.py#L139-L141)) in the library where log messages are emitted that come "out of nowhere" for a user. When using github3 as a library to automate some tasks on GitHub I was surprised to see the messages. What I don't understand is why I see these.

My library (from which I call github3.py) doesn't import `logging` anywhere, the code in github3 uses a package specific logger, and the default log level is warning so the info messages should not appear.

I searched for logging, logger and log to see if I could find relevant discussion but couldn't.

## Version Information
- The version of Python you're using: `Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)`
- The version of pip you used to install github3.py: 18.0
- Versions of github3.py (1.2.0), requests (2.19.1), uritemplate (3.0.0), and dateutil not installed
 

## Minimum Reproducible Example

I can't reproduce it with a minimal example. This is part of the mystery.

**Comment by lwasser** [comment]
yikes! cleaning up old things here... i think because we may move away from github3py we can close this BUT will reopen in the case that we see such issues in the future!
