### ISSUE TITLE
Check syntax for solutions and hidden tests

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#244]
These are some notes from the [earlier discussion](https://github.com/earth-analytics-edu/spring-2020-eapython-nbgrader/issues/34) about the `hidden` and `solution` syntax in nbgrader. 

What you put as _solution code_ (between `### BEGIN SOLUTION` and `### END SOLUTION`) represents what you want the student to create as their answer. It is only included in the `source` version of the notebook - it gets stripped out when creating the student version (otherwise, you would be giving them the answers). The purpose of this code is only for developing the assignment, so that you can validate / sanity check the instructions and what you think the solution should be.

What you put as _hidden tests_ (between `### START HIDDEN TEST` and `### END HIDDEN TEST`) are the tests that you want to run on the solution but not show to the students while they are completing their assignments.  

Here's how various nbgrader actions use these parts of the notebook:

* validate (as instructor): has access to hidden tests and solution code
* validate (as student): no access to hidden tests or solution code, only to student solutions and non-hidden code in tests cells 
* autograde: has access to hidden tests and student solutions (not instructor solution code).  
* feedback: shows all tests (hidden and non-hidden) and test output to students

As a concrete example, if you look at cells `In [13]` and `In [14]` in [this assignment](https://github.com/earth-analytics-edu/spring-2020-eapython-nbgrader/blob/master/source/ea-python-2020-01-flood-precip/ea-python-2020-01-flood-report.ipynb), the instructions ask the student to create objects called `calculated_year_*` (where * = `daily, monthly, yearly`) but the solution code creates objects called `*_max_year`, and the hidden tests use variables called `*_max_year`. The instructor validation would pass, but the autograding would fail, because the student would create objects called `calculated_year_*` and the hidden tests would throw and error about `*_max_year` not existing.

**Comment by lwasser** [comment]
Here is an example of tests using an external .py file 
https://github.com/earthlab/edsc-summer-2020/tree/master/python-fundamentals

**Comment by lwasser** [comment]
closing this because... it's autograding related rather than abc-classroom focused. there's no specific task associated with this issue.
