### ISSUE TITLE
Add Zenodo File to abc-classroom

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#252]
I'd like to cite abc-classroom and matplotcheck in a paper i'm working on! so we should

1. add a zenodo file with karen, nathan, tim etc on it... and 
2. create a new release just to ensure the citation is current with zenodo

**Comment by nkorinek** [comment]
@lwasser working on this right now!

**Comment by lwasser** [comment]
closing -- thank you @nkorinek !!
