### ISSUE TITLE
abc classroom token doesn't work when using across multiple computers

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#258]
I have a token already setup. I tend to work on multiple machines. The docs tell me to run abc-init however... i already have a token setup on github. SO... i think ideally this would check for a token, if it already exists then it creates the YAML file for me. Right now i'll have to either delete the token of create the file manually. 

[doc here](https://abc-classroom.readthedocs.io/en/latest/get-started.html)

<img width="761" alt="Screen Shot 2020-09-01 at 2 04 41 PM" src="https://user-images.githubusercontent.com/7649194/91900583-23345500-ec5c-11ea-8053-5654e0d327ff.png">

**Comment by kcranston** [comment]
I was worried that this was going to be more complicated, but I think we just need to ensure that the local file exists after we [check github for the token](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/__main__.py#L45), and write the file if it does not.

**Comment by lwasser** [comment]
i haven't tested this with the new PR but i can before we merge? hopefully it just works but if it is a bigger issues we can work on it separately too!

**Comment by lwasser** [comment]
this issue is pretty old and i think we've addresed it by adding GH token checks. closing.
