### ISSUE TITLE
ABC-CLONE -- puts all cloned repos in the main cloned_Repos dir - putting it in a sub directory with the assignment name would be more ideal

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#276]
Right now abc-clone places all repos in the main cloned_repos dir. this is not ideal given how many assignments a class will have.
it would be better if each assignment had it's own subdirectory in that cloned_repos directory which could then be used to store all of the repos.  this should be a small easy fix i think?

**Comment by kcranston** [comment]
This would be a fairly simple change - methods that underly both `abc-clone` and `abc-feedback` would need updating.

**Comment by lwasser** [comment]
thank you @kcranston @nkorinek why don't you work on this next? essentially just take the assignment name and create a directory to store all of the cloned repos in within the cloned_repos sub directory

so it would look like:

```
cloned_repos/
    assignment-name/
        student1-repo/
        student2-repo/
```

i hope the docs will be helpful for getting this to work!

**Comment by lwasser** [comment]
there are a few odd thins with abc-clone.

i just ran it on the hub AND locally. Locally it works.
locally i have ssh setup which maybe we can use that abc-init token instead of ssh setup? i'm just confused about how authentication works! 

on the hub i run it and get:

```
Loading configuration from config.yml
Could not clone or update the following repos:
 bootcamp-2020-04-plots-adamancer
 bootcamp-2020-04-plots-amap989
 bootcamp-2020-04-plots-bri33
 bootcamp-2020-04-plots-B-Pinke
 bootcamp-2020-04-plots-bridgetfloyd
 bootcamp-2020-04-plots-camrynsorg
 bootcamp-2020-04-plots-haselwimmer
 bootcamp-2020-04-plots-Ewolfe2
 bootcamp-2020-04-plots-fergusca
 bootcamp-2020-04-plots-esgeo
 bootcamp-2020-04-plots-epkennedy120
 bootcamp-2020-04-plots-
 bootcamp-2020-04-plots-frma6457
 bootcamp-2020-04-plots-gracehood
 bootcamp-2020-04-plots-Kernsjenl
 bootcamp-2020-04-plots-gnarledbranches
 bootcamp-2020-04-plots-kz-yamaguchi
 bootcamp-2020-04-plots-krantz23
 bootcamp-2020-04-plots-streamfireflies
 bootcamp-2020-04-plots-lwasser
 bootcamp-2020-04-plots-lrwives
 bootcamp-2020-04-plots-lisestdenis
 bootcamp-2020-04-plots-MECMccormick
 bootcamp-2020-04-plots-mred1208
 bootcamp-2020-04-plots-sutherm
 bootcamp-2020-04-plots-mike-petrut
 bootcamp-2020-04-plots-Mitch88
 bootcamp-2020-04-plots-
 bootcamp-2020-04-plots-nquarder
 bootcamp-2020-04-plots-nlamkey
 bootcamp-2020-04-plots-ColoradoJake1
 bootcamp-2020-04-plots-
 bootcamp-2020-04-plots-shelbyross
 bootcamp-2020-04-plots-tayjh445
 bootcamp-2020-04-plots-tjhallum
 bootcamp-2020-04-plots-c-andry
```
Because the exact same command works locally i can only guess this is an authentication issue. but i'm not sure what the issue is. maybe when we work on this command we also consider working on how authentication works. if we can use a local token based authentication for all operations it will be best for the hub. what does `abc-init` do in terms of authentication and is that token used for all API calls currently? it would be good to flesh this out further.

**Comment by lwasser** [comment]
ok closing this as it's implemented
