### ISSUE TITLE
abc-feedback pushes ds_store files back to the main repo

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#278]
is there a way to specify files to ignore in abc-classroom so it's not moving around files that we don't want to commit? 
i'm not sure the .gitignore is enough int his case. it would be good to have a check from a list of files in the config that are ignored...

**Comment by kcranston** [comment]
The `.gitignore` (assuming it is set up correctly) will ensure that these don't get pushed to back github. If we want to be selective about what gets copied, we could just copy `*.html` files. How confident are we that there aren't other files that we might want to copy in the future?

Trying to create an include / exclude list in the config that matches what `.gitignore` does is not at all trivial (we went down this path when discussing creating the assignment repos).

**Comment by lwasser** [comment]
ok i did implement this and it does seem to work well. closing!
