### ISSUE TITLE
weird bug - abc-feedback - can't find student repo

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#286]
This is really odd because the repos are clearly there and yet it can't find each one. 
it would be helpful for it to tell us the FULL PATH or where it's looking for the repo because it does exist in the `cloned_repos` dir as far as i can see. 

```
(earth-analytics-python) CIRES-EL-DM-041:fall-2020-abc-ea-bootcamp leahwasser$ abc-feedback bootcamp-03-github
Loading configuration from config.yml
Local student repository cloned_repos/bootcamp-03-github-adamancer does not exist; skipping student
Local student repository cloned_repos/bootcamp-03-github-amap989 does not exist; skipping student
Local student repository cloned_repos/bootcamp-03-github-bri33 does not exist; skipping student
```

version 0.0.15 (not the most recent release but the code for feedback hasn't changed)

**Comment by lwasser** [comment]
user error -- closing this with my "tail" between my legs thank you @kcranston for pointing out the fact that i can't spell correctly. i had the assignment name wrong

**Comment by kcranston** [comment]
The issue here was that the assignment name given as a command line argument to abc-feedback was incorrect (and therefore did not match the local directory names). It would be helpful to check that the assignment name matches local directory without student, and give a more helpful error message. Or, to at least print more information.

**Comment by lwasser** [comment]
oh goodness. i thought i was double checking user error but apparently my brain is a bit cloudy today. thank you again. 
I agree that a check would be helpful with a little warning note like -- hey did you spell the assignment name right? :)
