### ISSUE TITLE
default config setting for roster.csv

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#297]
the default github classroom roster name is `classroom_roster.csv` but we have `roster.csv` in the config. Should we consider making the default config value align with the default github classroom file name? that seems to make the most sense to me

**Comment by kcranston** [comment]
Fine by me. That's an easy fix (noting that the file downloaded from github classroom is fine for abc-classroom, but cannot be used as is for nbgrader - see https://github.com/earthlab/abc-classroom/issues/59#issuecomment-566827105)

**Comment by lwasser** [comment]
oops -- yes totally! i spent some time working on the roster for my class... i suspect we can easily write a little helper in the utils module to clean up a roster for nbgrader! then you just add it to the databse and it makes it much easier to grade as you have a student name + github id in the formgrader interface!
