### ISSUE TITLE
abc-feedback -- messages at the CLI are confusing

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#306]
When you run abc-feedback --scrub --github you would think it would tell you it's pushing to github but instead it says "doing nothing" `no changes... doing nothing` (see image below) which  is confusing. we should adjust the messages to ensure it correctly describes what it is doing. 
<img width="854" alt="Screen Shot 2020-10-09 at 10 07 21 AM" src="https://user-images.githubusercontent.com/7649194/95606231-469aae80-0a17-11eb-9fc8-ce82112d8bae.png">

i understand what it's doing but i think the messaging should be more clear

**Comment by kcranston** [comment]
That message is coming from the `git commit` part of the workflow ([code here](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/github.py#L156)), not the `git push`. If the feedback files have changed, then something strange is going on (i.e. the commit step should indicate that the repository _has_ changed).

**Comment by lwasser** [comment]
huh ok... maybe we need a more clear message? that would be easy to implement. it's just confusing because it says nothing to do but i want it to push the files!

**Comment by kcranston** [comment]
The `push_to_github` function does not print any output if it runs without error. We could certainly change this to print the stdout from the git subprocess command, which would tell you whether anything pushed to github vs "Everything up-to-date".

**Comment by lwasser** [comment]
this issue is still happening (abc classroom 0.1.9) BUT i'm not sure if we need to update the grading hub or not.

Ideally the message should be something like this:

When you run `abc-feedback -scrub assignment-name`

"I'm cleaning answers from the feedback file for student-username-here"

When you run `abc-feedback -scrub assignment-name`

"I'm cleaning answers from the feedback file for student-username-here and pushing to github -- success!!"

It would be much better to have friendlier messaging here. i'll tag this issue as a priority given it's been open for some time!!

**Comment by kcranston** [comment]
It would be good for abc-feedback to actually test for the presence of feedback files in the nbgrader directory.

**Comment by lwasser** [comment]
yes 
* check for presence of feedback files
* check for presence  of the dir to move to (student repo)

**Comment by lwasser** [comment]
Closing this for now...
