### ISSUE TITLE
nbgrader partial credit oddity

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#308]
Hi there - @kcranston 

we have a really odd issue that i can recreate locally. What happens - a student fails a set of tests and 0 is returned as the output. Yet the autograder gives them 5 points. i can give you the assignment, and all files needed but i just wondered... do you see anything odd in our tests looking at the image below? again i can share everything that you need to recreate this ! 

<img width="1016" alt="Screen Shot 2020-10-12 at 3 22 23 PM" src="https://user-images.githubusercontent.com/7649194/95791538-d1410f00-0c9e-11eb-8d58-51987cf72ba6.png">

**Comment by lwasser** [comment]
this could be an issue with our test - apparently it can fail with the correct answer too. but returns full points so maybe python is not getting the standard output because of our tests?

**Comment by lwasser** [comment]
@nkorinek i'm going to ping you here as i think something is off with our tests maybe??

**Comment by lwasser** [comment]
just a note that this issue relates to a bug in nbgrader that. @kcranston is aware of ! there is [an issue on the nbgrader repo as well](https://github.com/jupyter/nbgrader/issues/1374)

**Comment by kcranston** [comment]
Fixed and merged on nbgrader!

**Comment by lwasser** [comment]
really @kcranston ??!! https://github.com/jupyter/nbgrader/commit/f5729fb2b6638ea2c6f9b0f9226a0dd7c8cb2ad5 
we just did a hub update - OH but no release yet? how should we handle the install on the hub? keep as is or install from github (dicey)

**Comment by kcranston** [comment]
Last release was in [Nov 2019](https://github.com/jupyter/nbgrader/releases/tag/v0.6.1), so it might be a while before the next one. There are 161 commits between then and now, so I would want to do some testing before installing from github.
