### ISSUE TITLE
Abc-new-template vs update-template act differently

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#310]
when i run abc-new-template --mode merge --github 

it magically moves things over and pushes them to GH
when i run abc-update-template it doesn't accept the github flag but also sends me into a merge message interface rather than just doing it's thing. i thought the two commands were mostly the same with just different defaults but the behavior seems to be quite different.  they should be the same however

**Comment by kcranston** [comment]
Hmmm... interesting. Can I see the output from each? Both command line scripts call [the same function](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/template.py#L16). The `abc-update-template` command sets `mode=merge` and `github=True` before calling the function.

**Comment by lwasser** [comment]
so weird @kcranston so when i used `abc-new-template --mode merge --github` it just magically does everything for me.
When i use `abc-update-template` it brings up vi or something in my terminal, wants a commit message and such and so it is less magical. Is it possible that the default commit message isn't set for `abc-update-template`?

i haven't spent much time on this yet just noticed it was different today using it. i normally have just used abc-new-template but love the idea of having update do everything i want it to without the flags

**Comment by kcranston** [comment]
Ok, I checked the commit message part. `new-template` uses a default "Initial commit" message, see [help text](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/__main__.py#L169)  a good assumption if the template directory is indeed new) but `update-template` does not set a default commit message, so it opens the editor for you to enter one. We could set a default commit message for update, something like "Updating template repository".

**Comment by lwasser** [comment]
ok i spent some time on this too.. There are a few different text editor settings.

1. git global user preferred editor modified with `git config`
2. system text editor modified below (atleast this works on MAC) to be something other than VI

`export EDITOR="/Applications/Atom.app/Contents/MacOS/Atom"`

[here](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/utils.py#L210) you can see the [get_Editor() ](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/utils.py#L219)function which gets the users text editor

it defaults to vi if one is not set. i had my git text editor set but not the global machine one in my environment. i set it using the above and now get this
```
... more stuff up here... 
Copying extra files: 
 extra_files/earth-lab-logo-rgb.png
 extra_files/colored-bar.png
 extra_files/.gitignore
Empty commit message, exiting.
```

essentially it just keeps saying there's an empty commit and exits. i suspect that this is happening because atom is slow to open and not terminal based but i'm not sure how to add a ``wait`` flag like you can with gh.

so then i tried to change it to nano

```
export EDITOR=nano
``` 
that actually worked well. nano opened and i was able to add a message and close it . again the user does need to actually make that change to their global config for it not to default to VI. my config setting for `EDITOR` was empty so vi is the default.

**Comment by lwasser** [comment]
i think for now i have this documented well enough. it might be nice to set the text editor to the default github one in the future if we can as i think users would proably expect this behavior. but for now i added docs about text editors in this pr #338

**Comment by lwasser** [comment]
note #311 that will address this.

**Comment by lwasser** [comment]
## Text editor note - i'll move this over to the text editor issue. 
OK i see where this is coming from generally but don't know how to fix it yet

`os.environ.get()` is called in the utils module to support the commit message. there is an or `VI` so it defaults to VI if the editor get doesn't return a useful editor. i think we want to fix this but i'm not sure how. the environment variables frm that dont seem to include the git default editor 

`git config --global core.editor` this shows you what the default editor is. i wonder what happens if you dont have that or... would it just go to the default git editor?? anyway i can clearly see what is happening but don't know how to fix right now.

**Comment by lwasser** [comment]
i will close this as well. i know what is happening and added documentation #338 that overviews why these behave differently. in the above mentioned issue #311 we can address using the default editor rather than the global one (or checking for both?)
