### ISSUE TITLE
abc-clone moves notebooks only

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#312]
i've noticed this throughout abc-classroom.
It only moves notebook files and not .py files which is problematic. it should be an easy fix to move .py files to the submission directory.

one student just created a small module and called it. the notebook now won't run because the .py file wasn't moved.

**Comment by kcranston** [comment]
We could absolutely use the copy files helper function for this. And look! you already have a note about this: https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/clone.py#L133

**Comment by lwasser** [comment]
definitely. because abc-classroom in theory should be language agnostic i suggest we add another config item that provides it with a list of `files_to_move:` 
in our case we may chose to move .ipynb and .py files
in other cases they may have js and other file types. that is one option

the alternative is to move everything by default and have a second type of "ignored" files. 
i'm not sure what is best but someone could be teaching some other language and want to use abc-classroom.

**Comment by lwasser** [comment]
note i also mentioned this in #285 a while ago... i keep opening new old issues

**Comment by lwasser** [comment]
this  was actually also fixed with the above PR. we've added a feature that allows you to specify what file types you want to move. and then it moves them. the  default  is .ipynb but you can add a list to the config and move .py  or any other extension as well. closing
