### ISSUE TITLE
default branch is 'main' not 'master' now

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#327]
The new default branch name in GitHub is `main` not `master`. This affects our new repo creation. See attached screenshot with description of modifying local branch name before pushing. 

<img width="897" alt="Screen Shot 2020-11-11 at 5 30 41 PM" src="https://user-images.githubusercontent.com/312034/98871870-a2f05400-2443-11eb-9220-35c8f38eb803.png">

I've already got fixes for new repo creation in a local branch as part of my github authentication changes, but wanted to make an explicit note because it may create some confusion with new vs existing repos.

**Comment by lwasser** [comment]
oh!! that is right. i forgot that will impact abc-classroom. i've been slowing moving all of our older repos to main but didn't think about the tool implications! good news is we only have a few more classes left but we will have to tell the studnets about this change too!
