### ISSUE TITLE
test ssh setup for git operations as part of abc-init

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#366]
In addition to checking / generating an API token when running abc-init, we should also check that ssh access is set up correctly:

```
$  ssh -T git@github.com
Hi <username>! You've successfully authenticated, but GitHub does not provide shell access.
```

If ssh is not set up correctly, the error message will be:

`Permission denied (publickey).`

**Comment by lwasser** [comment]
please note that this test shouldn't only happen in abc-init - see #315 
So i think we should write a helper function that tests for ssh and run it both in `abc-init` and when you run `abc-clone` at a minimum! a helper would be great as we can then call it as  needed. we can't assume the user will need to run `abc-init` 

Given this issue i'll add it to the milestone associated with ssh tests!

**Comment by kcranston** [comment]
The places we would need to check for proper ssh setup before calling git are:

* abc-init script
* `push_to_github` method (called by abc-new-template, abc-update-template, abc-feedback)
* `pull_from_github` method (called by abc-clone)
* `clone_repo` method (called by abc-clone)

**Comment by lwasser** [comment]
yes please!! a helper will make that easy to check for each  function! :)
