### ISSUE TITLE
abc-clone - skip existing should have a default value of False

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#373]
this is an easy fix - update the doc string and then the function. it works well in the notebook!!

**Comment by kcranston** [comment]
This hurt my brain a little, but I think what we want is a change in default behaviour without the extra option and a renaming of the option to do the opposite thing. 

Current behaviour: 

`abc-clone assignment` -> clones repos that do not exist locally, and updates repos that already exist 
`abc-clone assignment --skip-existing` -> clones repos that do not exist locally, and does nothing for repos that already exist

Desired behaviour:

`abc-clone assignment` -> clones repos that do not exist locally, and does nothing for repos that already exist
`abc-clone assignment --update-existing` -> clones repos that do not exist locally, and updates repos that already exist

**Comment by lwasser** [comment]
i  think it 's good to leave this  open  as a few other weird t hings  are happening

Right   now -  issue to be  posted - `abc-clone`   is not working as expected. It seems to be asking  for authentication a gain f or each individual clone but then  not cloning  or pulling. 

locally i just  ran  `abc-clone --skip-existing `
It  gave me a lot of feedback that i didn't want -  see below and said  it copied files when it didn't copy anything. 
For me it actually created empty  clone directories for each student but it didn't clone  the content of the repo. 

```
Local repo cloned_repos/ea-2021-02-ms-remote-sensing/ea-2021-02-ms-remote-sensing-nlamkey already exists; skipping
Copying files from /Users/leahwasser/Documents/github/1-ea-python-course/2021/ea-python-spring-2021-abc/cloned_repos/ea-2021-02-ms-remote-sensing/ea-2021-02-ms-remote-sensing-nlamkey to /Users/leahwasser/Documents/github/1-ea-python-course/2021/ea-python-spring-2021-abc/nbgrader/submitted/nlamkey/ea-2021-02-ms-remote-sensing
Copying files to the: nbgrader dir
c-andry
Local repo cloned_repos/ea-2021-02-ms-remote-sensing/ea-2021-02-ms-remote-sensing-c-andry already exists; skipping
Copying files from /Users/leahwasser/Documents/github/1-ea-python-course/2021/ea-python-spring-2021-abc/cloned_repos/ea-2021-02-ms-remote-sensing/ea-2021-02-ms-remote-sensing-c-andry to /Users/leahwasser/Documents/github/1-ea-python-course/2021/ea-python-spring-2021-abc/nbgrader/submitted/c-andry/ea-2021-02-ms-remote-sensing
Copying files to the: nbgrader dir
toastferry
Local repo cloned_repos/ea-2021-02-ms-remote-sensing/ea-2021-02-ms-remote-sensing-toastferry already exists; skipping
Copying files from /Users/leahwasser/Documents/github/1-ea-python-course/2021/ea-python-spring-2021-abc/cloned_repos/ea-2021-02-ms-remote-sensing/ea-2021-02-ms-remote-sensing-toastferry to /Users/leahwasser/Documents/github/1-ea-python-course/2021/ea-python-spring-2021-abc/nbgrader/submitted/toastferry/ea-2021-02-ms-remote-sensing
Copying files to the: nbgrader dir
Great! All repos were successfully cloned!
(earth-analytics-python) CIRES-EL-LM-020:ea-python-spring-2021-abc leahwasser$ abc-clone ea-2021-02-ms-remote-sensing --skip-existing false
```

I think   for this issue maybe we tackle the  behavior of skip existing. and  h ave it

1. only  print  out  the repos that it founded that are new?
2. only  say  it copied  things for those repos IF it  actually copies  something

i think that we can handle the other issue of  it actually not cloning in the issue Nathan opens up.

**Comment by lwasser** [comment]
ok another thing -  if you run abc-clone twice for the same  assignment:
I  think  a nicer message could b e something like "there is nothing  to update in the  following repos"
This  will help us tease  out   when  things fail  because no  ssh is setup   vs when things are working but  t here is nothing to update in this case.

you get this feedback:
```
Could not clone or update the following repos: 
 ea-2021-02-ms-remote-sensing-adamancer
 ea-2021-02-ms-remote-sensing-brianpinke
 ea-2021-02-ms-remote-sensing-haselwimmer
 ea-2021-02-ms-remote-sensing-fergusca
 ea-2021-02-ms-remote-sensing-esgeo
```

so the  above two items - using skip existing vs just trying to update could use  better user feedback so we understand what is happening and not happening vs what is broken!
