### ISSUE TITLE
abc-clone asking for password for each student and not updating the repos

### ISSUE THREAD

**Issue by nkorinek** [earthlab/abc-classroom#376]
When running abc-clone on the nbgrader-hub, the hub asks for a password for each student that it clones the repo for. We have SSH set up on the hub, but it seems to still be looking for the token? I have to fill in my username/password for every single student. 
![image](https://user-images.githubusercontent.com/38253680/107821637-08e9c180-6d3a-11eb-9f6e-06713427fdd2.png)

Even if I go through and input my username/password for each student, it doesn't seem to be updating the students notebooks. We have one student that we're sure submitted changes to their repo since we lsat updated, and abc-clone hasn't updated their repo when it's run. 

For reference, this is what happens when I run abc-clone locally. It doesn't ask for my password, but it also doesn't appear to update my repos.

![image](https://user-images.githubusercontent.com/38253680/107821852-65e57780-6d3a-11eb-9757-119d6485bad3.png)

Very interesting problem, seems like maybe ssh and the old tokens are clashing in some way?

**Comment by kcranston** [comment]
What happens on the hub if you just type `git clone git@github.com:<org/reponame>`?

**Comment by kcranston** [comment]
or `ssh -T git@github.com`?

**Comment by kcranston** [comment]
Ok, after much troubleshooting on slack, there were two issues here:

1. The outer repo (the course repo) had been cloned with https, so when we ran git clone inside that repo, it wanted a username and password for authentication. The quick solution was to update the course repo to ssh. We need to think more carefully about the repos-within-repos design if we intend to keep the course directory under version control. 
2. The student repository had been updated in a fork, not in the earthlab organization. I need to check whether this should indeed result in a RuntimeError, or if there is something else going on. 

This all certainly points to better error handling / messages for abc-classroom.

**Comment by nkorinek** [comment]
Hey! Update on this bug. It seems that abc-clone is in fact having a hard time detecting when a student has changes pushed up to github. It seems like it has `--skip-existing` always set to true? But I'm fairly sure that `--skip-existing` is set to false by default. Here is the trouble shooting I have done. 

1. Mike petrut now actually has changes to their notebook pushed up to the correct repository. Seen here: https://github.com/earthlab-education/ea-2021-02-ms-remote-sensing-mike-petrut At the time of posting this comment, the changes are two days old.
2. When I run `abc-clone ea-2021-02-ms-remote-sensing` on the earthlab nbgraderhub, it goes through all assignments and says it couldn't update any of them. The latest changes on mike petrut's assignment on the hub show that it was updated 3 days ago (before they pushed changes) which means that the latest version of the notebook isn't on the hub. I confirmed this by looking at the notebook in `cloned_repos` and confirming the code hadn't changed. 
3. I then went to my hub, where I hadn't run `abc-clone` yet, and ran `abc-clone` there. The latest version of mike's notebook pulled down just fine and had the expected changes. 
4. On my hub, I deleted mike's folder for that week and reran `abc-clone`. This pulled down the latest version again. 

Not sure why, but it does seem that there is an issue with `abc-clone` not detecting changes on students repos. Just wanted to document my trouble shooting here. I'm going to delete mike's folder on the earthlab hub and rerun `abc-clone` to force the repo to update.

**Comment by kcranston** [comment]
For the repos that it doesn't update, do you see the message "Local repo <name> already exists; skipping"?

**Comment by kcranston** [comment]
There was indeed a bug, but not with the `--skip-existing` flag. Hadn't changed the default branch to `main` for the git pull method, which was failing silently.

**Comment by lwasser** [comment]
oh no  way @kcranston ok so we were seeing some odd behavior but it was wrapped up  into several different issues! thank you for catching and fixing!

**Comment by nkorinek** [comment]
Nice catch!!! Explains a lot, thanks!
