### ISSUE TITLE
abc-clone  - when you mis spell an assignment name it creates a blank directory

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#377]
Here nathan  i believe misspelled th e assignment and a  new directory appeared  for  the  ms-remote-sensing  assignment

<img width="623" alt="Screen Shot 2021-02-12 at 2 33 11 PM" src="https://user-images.githubusercontent.com/7649194/107824818-5583cb80-6d3f-11eb-8c11-b2f11019b73a.png">

I suspect that this is related to what i added to organize files. i am not checking  that  the assignment exists before  creating the directory! i'm pretty sure  that is what i did wrong here and what needs to be  fixed

**Comment by kcranston** [comment]
Yup - the first thing that clone does is [check that the assignment directory exists](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/clone.py#L107) and creates it if it does not. It has no way of knowing whether this is a misspelling or not. This gets us back to the assignment management / database question.

**Comment by kcranston** [comment]
The clone script could instead fail if the assignment directory does not exist. Would that be better behaviour?

**Comment by lwasser** [comment]
@kcranston yes  please!! Ideally i  think   it  should do this

1.  look for an assignment  directory with that name AND with something inside it to move
    * If  it finds the directory but  its empty - tell the user - OOPSIES i found  the assignment directory but it  looks empty"
    *  if it finds files inside, continue ...
2.  If continue - create  the new directory and try to  clone. 
this will address that  bug and also  nice friendly error messaging! thank you!!!

**Comment by lwasser** [comment]
this was fixed here - https://github.com/earthlab/abc-classroom/pull/295 closing
