### ISSUE TITLE
helper function for file copy

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#382]
There are a couple of places where we copy files from one location to another:

* the [`copy_feedback-files`](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/feedback.py#L17) function in `abc-feedback` copies from nbgrader/feedback to the student repos
* the [`copy_assignment_files`](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/clone.py#L177) function in `abc-clone` copies from student repos to nbgrader/submitted
* the other [`copy_assignment_files`](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/template.py#L236) function in `abc-new-template` and `abc-update-template` copy from nbgrader/source to template repository

All of them have various rules about what gets copied and what doesn't. Can we write a single helper function that does all of the filtering and copying? Notes about copying files:

* For `abc-clone`, it looks for `files_to_grade` in the config files and _only_ copies files (and directories?) that match the list
* For the template scripts, we look in the config file for `files_to_ignore` and copy everything _except_ things in that list 
* For `abc-feedback`, we look look for html files and then filter that list against the `files_to_ignore` in the config
* Template repositories also contain a `.gitignore` that defines what does not get pushed from the local repo to github (gets applied after `files_to_ignore`, so may ignore additional files). This affects the `abc-template` scripts but not `abc-clone`
* In general, we want to avoid copying 'system' files and directories (.ipynb_checkpoint, .DS_Store, etc)
* We want consistent behaviour for subdirectories (recursively copy?)

**Comment by kcranston** [comment]
Ah, there is also the `copy_extra_files` function for the template scripts. We need to deal with moving directories here, too (see error in #358 where `extra_files/.github` is a directory)

**Comment by kcranston** [comment]
Pondering whether all of the copy functions can use an inclusion list rather than an exclusion list. I imagine that there is a short list of file types that you want to copy from `source` (and that might be shorter than the list of things _not_ to copy?). I think this makes the code simpler - you can just `glob` for matches and copy those. Also makes usability better, because you are always specifying what to copy rather than a combination of what to copy / what not to copy, depending on the script. 

Questions for @lwasser and @nkorinek :
* would an inclusion list work for `abc-feedback` and `abc-<new/update>-template`?
* would the list of files to copy be different for each of the three use cases listed in the first comment of this issue?

**Comment by kcranston** [comment]
Question about copying feedback. Do we want to only copy `.html` files, or all files in `feedback` dir that aren't on an exclusion list? 

Currently, in the `copy_feedback_files` function, we do a combination - we glob for `.html` files, and then check that list of files against the exclusion list in the config (i.e. both an inclusion and an exclusion filter). If we want to keep this behaviour, then the copy_files helper as implemented won't work for `abc-feedback`.

**Comment by lwasser** [comment]
oooh good  question. let  me  think this  through

for  copy template  we may want
* .py,  ipynb and  the .github dir, images etc etc

for feedback, right now  we only have html files. i've never had  to push anything else  BUT... i could see a use  case for wanting  to include say a notebook with the answers or a .py file.  @nkorinek do you have any thoughts on this?

**Comment by nkorinek** [comment]
@lwasser this function can be closed too!
