### ISSUE TITLE
better  error  handling: Sample Roster not found

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#384]
when running  `abc-clone assignment`  abc-classroom looks for  the  roster.
I just ran it  and  got  the error below. it's odd  because that file does exist. it could be  helpful to  provide a better  error message that tells me the  full path to  the  file  it is  trying  to find with a friendlier message. in this case  the  file   does exist.
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/abc-clone", line 8, in <module>
    sys.exit(clone())
  File "/opt/conda/lib/python3.8/site-packages/abcclassroom/__main__.py", line 86, in clone
    clone_student_repos(args)
  File "/opt/conda/lib/python3.8/site-packages/abcclassroom/clone.py", line 62, in clone_student_repos
    clone_repos(assignment_name, skip_existing, no_submitted)
  File "/opt/conda/lib/python3.8/site-packages/abcclassroom/clone.py", line 171, in clone_repos
    raise FileNotFoundError(
FileNotFoundError: Cannot find roster file: xsample_roster.csv
jovyan@jupyter-lwasser:~/test-abc/myclass$ pwd
/home/jovyan/test-abc/myclass
```

NOTE: i am working on the ea-hub - no ssh  is setup there

<img width="726" alt="Screen Shot 2021-02-18 at 6 47 10 PM" src="https://user-images.githubusercontent.com/7649194/108445495-bae12c00-7219-11eb-9f03-c1c3ad3ed460.png">
<img width="491" alt="Screen Shot 2021-02-18 at 6 47 03 PM" src="https://user-images.githubusercontent.com/7649194/108445496-bb79c280-7219-11eb-906e-a3620759e82c.png">

*****

this gets weirder - how did it  FIND the  roster running `abc-feedback`  but not running  `abc-clone`?
what did i break?

```
jovyan@jupyter-lwasser:~/test-abc/myclass$ pwd
/home/jovyan/test-abc/myclass
jovyan@jupyter-lwasser:~/test-abc/myclass$ abc-feedback assignment
Loading configuration from config.yml
Local student repository cloned_repos/assignment/assignment-username does not exist; skipping student
Local student repository cloned_repos/assignment/assignment-username does not exist; skipping student
jovyan@jupyter-lwasser:~/test-abc/myclass$
```

**Comment by kcranston** [comment]
I think this is related to the conversation we had yesterday about not treating paths consistently throughout abc-classroom.  Should be a relatively easy fix!

**Comment by lwasser** [comment]
makes  perfect sense!! i'm  happy to  test  again  next  week
i could  also  poll  twitter  about  thoughts on dependency checks?  because not  everyone uses  ssh  it could be nice  to  check for  it. windows users should have git  if they  use github of  course but ssh is  not something that everyone  uses.

**Comment by paola-md** [comment]
Super quick and temporal fix: Running the function clone_repos() from course-directory

**Comment by lwasser** [comment]
hi @paola-md thank you for this input! are you using abc-classroom?

**Comment by paola-md** [comment]
Yes! I love it! It has been very useful :) 
The documentation and the code are very clear and it has saved me a lot of time and frustration. Thank you!

**Comment by lwasser** [comment]
wow thank you for that feedback @paola-md  !! i'm so glad that it is useful. we are now working on troubleshooting bugs and better error messaging. open to all feedback when you run into issues please post them for us to consider!

**Comment by nkorinek** [comment]
@lwasser this can be closed now!
