### ISSUE TITLE
Default editor for `nbdistribute`

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#39]
When asking the user for a commit message we check the `EDITOR` and `VISUAL` environment variables to try and figure out what (command-line?) editor the user prefers. If we can't find anything `vi` is used. There is no particularly good reason to use `vi` as fallback.

There are two things to do:
* are there more variables or places we can check to find out what editor the user would like us to use?
* decide what the default editor should be

**Comment by lwasser** [comment]
oh gosh that would be great. i was good for me as it forced me to learn vim this weekend. But i have atom set as my default editor. we can't assume all users will have atom installed but it would be nice if it would find our default editor rather than defaulting to vim!
