### ISSUE TITLE
Submit to JOSE / JOSS / Pyopensci??

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#408]
sounds like [JOSE](https://openjournals.readthedocs.io/en/jose/submitting.html) might be  best following @jedbrown  s suggestion and looking at the  requirements i agree it looks like a great fit!

@kcranston  let's make this our summer goal to get this submitted there!  i  wonder if i should  then consider  a partnership with JOSE as well for education software via pyopensci  in  the future <side note> :)

**Comment by kcranston** [comment]
JOSE [submission requirements](https://openjournals.readthedocs.io/en/jose/submitting.html): 

* Have the software available in an open repository (GitHub, Bitbucket, etc.) under an OSI-approved license.
* Write a short Markdown file titled paper.md with title, author names and affiliations, containing a description of the software, statement of need, and key references.
* References should be included in a BibTeX file called paper.bib

Their [review criteria](https://openjournals.readthedocs.io/en/jose/review_criteria.html) for software includes:

* Documentation: The software repository should contain enough documentation to understand the functionality of the software, to guide through the build process (including a list of dependencies), and to complete examples of use.

* Tests: Software quality depends on testing. Ideally, the software should include an automated test suite, but it’s also acceptable to include documented manual steps to test the functionality of the software.

* Examples: Potential users of new software rely on well-documented examples to get started. Reviewers will look for examples of use that illustrate beginner and advanced functionality

**Comment by kcranston** [comment]
Hackmd readme: https://hackmd.io/@LtZ1RDU9RP2lWTzmwNiadw/r1ya8vXEt/edit

**Comment by jedbrown** [comment]
Was this nixed or done?
