### ISSUE TITLE
Scrub token from terminal output

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#41]
Scrub all print outs/tracebacks so that they do not contain access tokens.

This probably means we need to wrap all calls in `try: except:` blocks where we customise the printouts. Currently some of the `git clone` calls will reveal the users personal access token in the log. They might then copy&paste that to a help forum or similar.

**Comment by lwasser** [comment]
i suspect we can close this as well as there is no longer tokens involved (i think) with our github operations. as it's mostly just requests. @kcranston if i am incorrect ehre please reopen this!! i'm just doing some cleanup.
