### ISSUE TITLE
Cannot create new assignament

### ISSUE THREAD

**Issue by danski3456** [earthlab/abc-classroom#418]
I have been following this [link](https://classroom.github.com) to set up nbconvert + abc-classroom but it is not working

I am getting the following error:

![image](https://user-images.githubusercontent.com/49415614/123331536-cae58100-d515-11eb-86e5-167d7d685d4a.png)

**Comment by kcranston** [comment]
Can you post a bit more about which abc-classroom command is giving the error? It looks like `abc-init` is working without error, but the previous command is failing (but I can't see what you ran that generated that error).

From what I can see, it looks like you are trying to create a repository in a GitHub organization that you do not have permission to create repos.

**Comment by danski3456** [comment]
My bad, I forgot to add the `abc-classroom-bot`  to the organizatino.
