### ISSUE TITLE
Circle CI failure

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#42]
hey @betatim so i submitted a test partially complete assignment over the [weekend her](https://github.com/earth-analytics-edu/ea-spring-2019-lwasser/commits/master). See last commit: 3de3e428081703ba5e1b546191c8c21f0bc4c2ce 

Circled Ci failed to run it LOOKS like it was hung up in the ok module 

Here is my assignment
https://github.com/lwasser/autograded-course-starter/blob/master/master/week-05/time-series-homework-wk-5.ipynb

I think i may need to clean it up more but am not sure where we landed with the points and grading. Can you kindly have a look so i better understand what's going on with circle ci?

**Comment by betatim** [comment]
Not sure what happened. My guess at the moment is: somehow old and new versions and stuff? Which is not super helpful.

The error comes from a notebook in the `week1` folder.

Maybe the thing to do is to remove all the cruft and old stuff from the starter repository and start with a clean slate?

**Comment by lwasser** [comment]
I will do that. i think us building a clean course starter will be great.
