### ISSUE TITLE
Organization of github and git functions in abc classroom

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#447]
Currently we have some functions:

`get_github_auth()` and `set_github_auth()` in the config.py module. But we also have a github module. When writing tests it seemed to make more sense to have all github things in one module. And perhaps git things in another??? 

Let's talk here about how we want to organization abc-classroom to ensure things are easier to maintain in the future.

**Comment by lwasser** [comment]
As i'm working on this and watching the test file get HUGE... what if we had a module with github specific things and a module with git specific things?

alternatively we could consider a git authentication module and a github module.

All of those helpers that check ssh, authenticate, etc could be in the authentication. i'm just thikning we want to reorganize as this is a really huge module (github.py). maybe i'll make a list of functions and we can collectively organize them using a list here?

**Comment by lwasser** [comment]
## Github.py - Current list of functions
- [ ] `get_access_token()`
- [ ] check_git_ssh()
- [ ] _get_authenticated_user(token)
- [ ] _get_login_code(client_id)
- [ ] _poll_for_status
- [ ] _call_git
- [ ] remote_repo_exists(org, repository, token=None)
- [ ] clone_repo(organization, repo, dest_dir)
- [ ] create_repo(org, repository, token)
- [ ] add_remote(directory, organization, remote_repo)
- [ ] repo_changed(directory)
- [ ] new_branch(directory, name=None)
- [ ] get_commit_message()
- [ ] commit_all_changes(directory, msg=None)
- [ ] init_and_commit(directory, custom_message=False)
- [ ] _master_branch_to_main(dir)
- [ ] push_to_github(directory, branch="main")
- [ ] pull_from_github(directory, branch="main")
- [ ] git_init(directory, defaultbranch="main")

## config.py functions
- [ ] get_github_auth()
- [ ] set_github_auth(auth_info)
- [ ] get_config(configpath=None)
- [ ] print_config(config=None, configpath=None)
- [ ] write_config(config, configpath=None)
- [ ] get_config_option(config, option, required=True)
- [ ] set_config_option

**Comment by lwasser** [comment]
i just realized we also have functions with the same name. there is git_init in both the github module and the distribute module.

**Comment by kcranston** [comment]
I made a few changes, consistent with PR #452 . This allows us to have all of the CLI git / subprocess calls in the same place. I like the idea of separating the auth functions.
