### ISSUE TITLE
Clean up old / deprecated code

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#449]
there is a lot of code in abc-classroom that is a result of the original workflow. We are no longer using this so it would be nice to finally clean / remove this code from the code base for easier / cleaner maintenance. 

Some of this code is just commented out now (see the github.py module).

There are also full modules that we don't use including ok.py . There's some great code in there that was actually a nbgrader free grading system. It would be good to archive this in case we ever want to use it but remove it from the package if we aren't using it..we could create a release and or branch to archive

**Comment by kcranston** [comment]
Addressed by PR #454
