### ISSUE TITLE
break up get_access_token into two helpers?

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#460]
Currently, [`get_access_Token` is a single function](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/auth.py#L61). It was throwing me off for a while because i thought it did one thing but it actually does two things. both involved getting the token but via diff paths.

First, it checks to see if a token is local and valid and if that passes you are golden.
If that check fails, then it goes on to authenticate with GH and make a new token. 

I wondered if we wanted to break those two sections into two helpers so the final function would be something like this

``` python
def check_for_token():
  if _get_access_token:
     # assuming this may return a boolean
     # check to see if a valid token exists and return True
     print("yay happy message")
  else:
     _create_new_user_token()
return ??
```

@kcranston what do you think about this?

**Comment by kcranston** [comment]
Sure, that's an easy fix. It doesn't need to return anything, since the [only place we use that in abc-init](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/__main__.py#L40) doesn't capture / need a return value.

**Comment by lwasser** [comment]
it's funny this isn't a huge issue but for testing i'm finding it cleaner to have simpler functions. :)
