### ISSUE TITLE
Function that may not get used anywhere in abc classroom

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#465]
I am writing tests for the git module and [happened across, here](https://github.com/earthlab/abc-classroom/blob/main/abcclassroom/git.py#L125)

`new_branch(directory, name=None)`

I can't find any function in the code base that calls this command. Is this a remnant from the previous functionality? Can we safely get rid of it?

I won't write a test until i'm certain it's required. i don't think it is but want a second opinion before i remove it.

**Comment by kcranston** [comment]
That should definitely be deleted. I thought I had done that, but I must have missed it.

**Comment by lwasser** [comment]
closing via #467 thank you @kcranston !
