### ISSUE TITLE
Branches build up in student directories

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#47]
Currently each time i merge a PR, the branches in that repo build up (please see image below). I think we need to clean up the branch created each time by the PR. otherwise it could get difficult to manage. i am not sure what the best approach to this would be. One option could be to clean up the previous branch each time a new pr is created? so then there is always just one branch that is there unless the student deletes it when they merge the PR. Or could the PR come from the template repo rather than from a branch within the student's repo? that would be the cleanest option. i'm just unclear as to what is happening with this PR process. 
<img width="341" alt="screen shot 2018-12-18 at 4 10 35 pm" src="https://user-images.githubusercontent.com/7649194/50188651-8b53d380-02df-11e9-8a41-fe40a60b0896.png">

**Comment by betatim** [comment]
I think we could delete old branches when we make a new PR. Important to check if a branch has been merged (or the corresponding PR closed) before deleting them.

My feeling was that using the template repository as the source of the PR would be trickier. The thinking was:
* we still need a way to clean up
* we need to generate a diff/PR that brings that student's repo up to date. It wouldn't be the same for all students (for example if you didn't merge last weeks PR you need a different one this week compared to someone who did merge it)
* we need to add lots of remotes to the template repo (one for each student)

So I'd investigate automatically cleaning up old/stale/unused branches when we create a new one.
