### ISSUE TITLE
Do we want to keep python 3.6 support & docs build

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#481]
Python 3.6 is now at [end-of-life](https://www.python.org/downloads/release/python-368/) and we have our first test failure due to incompatible version, #479 

Any reason that abc-classroom should keep supporting 3.6? If not, we should update our Actions workflow to stop testing that python version. Alternately, we'll need to make some modifications to the dependencies.

**Comment by kcranston** [comment]
This particular action is only to build the docs, so one option is to simply restrict the tests that build the docs to >3.6 (i.e modify the python version matrix for that action).

**Comment by lwasser** [comment]
if we drop 3.6 it makes sense to add 3.9 i think. Do we want to do this ? i'm willing to try it to see if tests and builds pass on 3.9 but i suppose we know our test suite is questionable so perhaps it is not a good idea now?
