### ISSUE TITLE
Meta issue on creating documentation

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#49]
We will create a clean, new, simple example repository ([the `course-starter` repo](https://github.com/earthlab/abc-course-starter)) that people can use to start a new course. It will contain:
* two or three simple notebooks/assignments that show off how to create private/public tests, different points per assignment
* explanation of what can and can't be in different cells (depending on what tag they have)
* markdown explanation of how to create tests, comments, stuff
* annotated but with gaps `config.yml` that will be filled out by readers when they follow the quick start

---

Create a way to have a "dummy-student" directory locally that you can "distribute" to and then "grade". It would allow the instructor to pretend to be a student, attempt the assignment, see what the assigned grade is.

---

There will be [a quick start guide](https://hackmd.io/0ZbGctpuSdqYK2OdPI51dw?view) (hackmd to get going) to walk people through the process of creating a new class based on the quick start repository.
* will walk reader through the process of starting from the `course-starter` repo and end with them having a fully working course
* instructions for simulating the grading/rendering of the student notebook

---

This quick start guide will be part of the documentation (RTDs) that is in this repository.

---

There will be additional documentation about the components in this repository as well.

**Comment by lwasser** [comment]
closing this as we have redone the documentation!
