### ISSUE TITLE
setup readthe docs for abc-classroom

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#50]
* Setup with readthe docs and then add the template dir using sphinx.

**Comment by betatim** [comment]
Two quickstart guides that I've followed before. I think I mostly follow the first one but read the second one in parallel to see when they deviate:
1. https://www.sphinx-doc.org/en/master/usage/quickstart.html
2. https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html

**Comment by lwasser** [comment]
Thank you so much @betatim !! see this pr: https://github.com/earthlab/abc-classroom/pull/52 now building successfully.

**Comment by lwasser** [comment]
https://abc-classroom.readthedocs.io/en/latest/ closing this - implemented
