### ISSUE TITLE
Only add specified assignments/files 

### ISSUE THREAD

**Issue by betatim** [earthlab/abc-classroom#51]
Right now `abc-author` adds all assignments to the student directory. Similarly `abc-distribute` will generate a PR that modifies everything.

Instead we want to have `abc-author assignment1` which only adds assignment1 related files to the already existing `student/` directory. `abc-author -d assignment1` would remove the assignment from the `student/` directory again.

`abc-distribute` (w/o arguments) would generate a PR based on everything in `student/` (copy over whole `student/` directory). `abc-distribute assignment1` would only create a PR with changes for that assignment (copy over only the assignment specific sub-directory from `student/`).

One thing that will be tricky to figure out is the `.circleci/config.yaml` which we will need to edit as we do this.

**Comment by lwasser** [comment]
I had another thought about this yesterday @betatim Right now what works well is each time i distribute content we reset the PR in the student's directory. This handles the student that maybe misses the first assignment for whatever reason or any assignment. Is there a clever way to still ensure that we don't get PR merge conflicts for the students?

**Comment by lwasser** [comment]
closing this for the time being as we are using nbgrader now!
