### ISSUE TITLE
Handling Student Rosters - issues to address

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#59]
There are a few ways to handle rosters in our current grading workflow. Here are some of hte issues

1. If you download the roster from github classroom, it has an identification column. However nbgrader needs an id column. you can rename the identification column to ID however several issues arise when you do that. 
  - [ ] Could nbgrader be updated to accept both id and identification? OR should we add a roster cleanup step that adds all required columns to that github downloaded roster? it could just be a little helper function
2. If you create your own roster, there is no template for what that should look like.

@jlpalomino can you kindly add some clarification around the pieces needed in a roster? i think we just need to streamline our scripts to ensure all of the pieces are there. Will a first and last name ever be available in the github classroom roster? ie if you add me as a student will my first name and last name be there?

**Comment by lwasser** [comment]
@kcranston this is the student roster issue that we will need to address when you are implementing the feedback piece and for grading.

**Comment by kcranston** [comment]
Exporting the roster from GitHub Classroom gives the following columns (where `name` is not always present in each row): 

`"identifier","github_username","github_id","name"`

While the nbgrader import format has the following columns (only id is required, all others optional):

`"id", "first_name","last_name","email","lms_user_id"`

The obvious mismatch is that `id != identifier` but it is slightly more complicated:

* the contents of the `identifier` columns in the github roster is not consistent. Based on three different classrooms, I see 'Firstname, Lastname', email address, and github username as the identifier (and sometimes differences between rows in the roster for the same class)
* what we really want to match is nbgrader `id` with github `github_username` - consistently using github usernames as the identifer in the abc code ensures that we accurately match the downloaded repository with the nbgrader subdirectories. 

The simplest thing might be to have an abc-classroom script for validating the roster and (optionally) reformatting to what nbgrader expects (which would simply be adding an `id` column with the github username. 

Currently, abc-classroom only requires that the roster contains a `github_username` column.

**Comment by lwasser** [comment]
yes totally! i spent some time working on the roster for my class... i suspect we can easily write a little helper in the utils module to clean up a roster for nbgrader! then you just add it to the databse and it makes it much easier to grade as you have a student name + github id in the formgrader interface!

**Comment by kcranston** [comment]
Question - in your current workflow, where do you get the student first name and last name and how do they get into the roster? Do you download that list from some other system? and then input the names manually into the roster?

**Comment by kcranston** [comment]
We discussed this on a call, but I forgot to update the issue. The first name and last name come from the GitHub Classroom roster `name` column (if the student has added their name to their GitHub profile). So, the roster utility can do a simple split on the first whitespace in the `name` column to create the first and last columns. There might be some manual cleanup required, but this would be a good first pass that works in the majority of cases. 

Having the first name and last name is really handy for nbgrader so that you don't have to recognize github usernames that bear no relation to the student name!

**Comment by kcranston** [comment]
Question for @lwasser : If a row in the input roster does not contain a github username, do you want to: 

1. Include that row to the output roster
2. Skip printing that row for the output roster 

(For example, when you download the Github Classroom roster for the ea-python-spring-2021-abc class, there are rows for "Leah Wasser" and "Test Student", but those rows only contain information in the `identifier` column).

**Comment by nkorinek** [comment]
@lwasser this issue can be closed I believe!
