### ISSUE TITLE
add abc-classroom to conda-forge

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#61]
straight forward task. just need to start it.

**Comment by lwasser** [comment]
i started this here

https://github.com/lwasser/staged-recipes/pull/1 

@kcranston just curious -- what "tests" should we run for a CLI tool? for matplotcheck we simply test importing various modules. could we do something similar here? this tool just seems a bit different than the other two we have on conda forge.

**Comment by kcranston** [comment]
There are some good examples in the [docs for adding packages](https://conda-forge.org/docs/maintainer/adding_pkgs.html#test). At the very least, seems we should test that it imports correctly, and that you can run one or more of the CLI scripts with ``-help``.

**Comment by lwasser** [comment]
this has been done -- https://github.com/conda-forge/staged-recipes/pull/12628 !! i was shocked how fast they were in just accepting it this time :) closing. thank you @kcranston i just kept the import statement simple as you and i discussed yesterday!!
