### ISSUE TITLE
Get started with classroom!

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#64]
* go through contributing.rst file, and setup dev envt. Does it work? 
* see if you can get `abc-init` to work. If it does work for you, document how it works in the hackmd document (just add a new section) 
  then update the docstrings associated with the functions that it uses

**Comment by nkorinek** [comment]
This issue addressed here: https://github.com/earthlab/abc-classroom/pull/66

**Comment by lwasser** [comment]
thanks @nkorinek closing this!!
