### ISSUE TITLE
Create rst file for nbgrader class setup 

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#77]
Following the notes here you can create an .rst file that describes the nbgrader class setup. 
Create section on assignment setup here too. 

* https://hackmd.io/_4GDiG9wSwe6lBq18bDM7w#Step-4-Setup-nbgrader-repository
* https://hackmd.io/_4GDiG9wSwe6lBq18bDM7w#Create-an-Assignment

Create-an assignment might work well as a separate page.

**Comment by kcranston** [comment]
I think this is now done with PR #166

**Comment by lwasser** [comment]
hey there @kcranston i'm digging around for this info. is it in the docs? i don't see it but i'm also doing a very quick scan! what i was hoping to create is a little nbgrader cheat sheet for things we do a lot. and i had started this i think somewhere but it was not pretty. i don't want you to worry about creating it but just want to ensure that i am not missing something before working on it.

**Comment by kcranston** [comment]
There only place we discuss nbgrader is in the [creating course materials](https://abc-classroom.readthedocs.io/en/latest/course-materials.html#managing-course-materials-using-nbgrader) page. You are welcome to add more!

**Comment by lwasser** [comment]
i am going to close t his issue. i have a google  doc going with more specifics about all of this but we have actually done a lot of documentation refactoring!
