### ISSUE TITLE
Create assignment Template Repo

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#82]
There are several steps associated with creating the git template repo locally. These include

## 1. Making the assignment directory:
- [ ] Here we want the user to specify where the template repos live as an option. But the default behavior is that it creates the repo in:
     - `assignment-repos` which lives outside of the nbgrader repo.
  so the dir structure looks like this

```
nbgrader-classroom-dir/
assignment-template-repos/
    assignment-one-template/
    assignment-two-template/
```

Note that the example above assumes assignment-one is the name of the assignment. the repo name comes from the assignment name. 

## 2. Move files to the directory
I'm using move files because add is a git thing too.  In this step we need to move all of the files
The files we will move include:
1. [readme, .gitignore](https://github.com/earthlab/abc-classroom/issues/79) over to the newly created template repo created above in step one. 
2. any other files that we may need like a header image file (perhaps those could go in a directory that can be used to collect all additional files that may be needed in all repos?? i'm not sure but i'm thinking about the image header file as an example 
3. released assignment files
Because i'm wondering if this workflow could be used outside of nbgrader in the future and with rmd files too let's think about how this could work. The default could be that it looks for the assignment name in the release. but perhaps that could be customized in the future via the config file? what i'm getting at here is that i don't want to only move .ipynb files over just in case we move to something different in the future. or i want the flexibility her to allow for other file types. 

## 3. Initializing the directory and committing files
  - this step includes committing added files to it

ABC [Classroom has git init which initiatlizes and adds](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/distribute.py#L43) - jed's approach seems to do many things in a single function (do local git things) including finding files and such. i'm not sure we need to do that. i'd rather a function that just does the commit and init steps and move the files separately. **I suggest we use abc-classroom's git init here.** 

Finally
4. Create repo on github and then push the repo to github.
In the scripts the github piece is manual. but in abc-classroom, [you can create a repo and then push there. ](https://github.com/earthlab/abc-classroom/blob/master/abcclassroom/github.py#L113). Here i suggest that we use the functionality of this to create and push to github.  Here is what i am uncertain of - i'm uncertain of whether abc-classroom here creates the new repo on gitjub. it looks like[ a repo is being created here: ](https://github.com/earthlab/abc-classroom/blob/6c61efee65f9eb447920025b091aa1ea70a7224a/abcclassroom/__main__.py#L290). This seems buried. id rather see a helper function for create-repo-on-github that is called in main that lives in the github module. so let's use this code but move it out of main and call it from main! This seems cleaner to me.  

here is the [actual call to create the repo nested within a loop
](https://github.com/earthlab/abc-classroom/blob/6c61efee65f9eb447920025b091aa1ea70a7224a/abcclassroom/__main__.py#L295) this was this way because we were pushing each repo to github classroom rather than allowing it to create the repos for each student! let's pull this code out!

**Comment by lwasser** [comment]
Hey @kcranston i've created two issues surrounding what i called step 4 in the meta issue associated with merging jed's workflow with this one (#58). I think these are a great starting place. i went through and aligned what jed did with what abc-classroom does. if you'd like to break these out into small issues as well please say the word but i thought we could start here!

i think resolving these will actually be huge progress for us in our workflow!! @nkorinek is working on documentation now and cleanup. If you are working specifically he is updating docstrings for the github module. if you will be working on that module (i'm guessing you will) it could just be good to coordinate with him or i can help with the coordination too!!  he works tues-thursday!

**Comment by lwasser** [comment]
please note that [this issue](https://github.com/earthlab/abc-classroom/issues/73) also refers to using the config file. i think i've captured it here and in the other issue but just trying to stay organized!!

**Comment by lwasser** [comment]
@kcranston this is an issue i'd like for you to work on!!

**Comment by kcranston** [comment]
What behaviour do we want when the (local) template directory already exists? In the current [make-template-repo](https://github.com/earthlab/autograding-notebooks/blob/master/scripts/make-template-repo.py) script, we simply fail if the directory already exists. Options (assuming warnings for any option):
* Continue in the existing dir, adding new files / overwriting existing files - this could leave an uncertain state depending on what you added or changed in the config / notebooks
* Delete everything in the existing dir and then continue (somewhat scary)
* Create a new dir with some different name, link this one to GitHub, and let the instructor clean up afterwards (e.g. `rm olddir`, `mv newdir olddir`)

**Comment by lwasser** [comment]
ok lemme see @kcranston ... so you are asking, 
the instructor has a dir structure like this:
```
class-name-nbgrader/
assignment-one-template/
```
Then they try to create the assignment-one template repo and you find that the dir already exists. if i understand this correctly, i'm wondering if we can have flags

no flag - returns a warning (doesn't do anything) that says `oops, looks like that directory already exists, you can overwrite it using -f (or whatever we want the overwrite flag to be i was thinking f for force but what is normal). or -o for overwrite ??`

that way they can enter the dangerzone by choice if they want but that's not the default behavior. The next question then is

1. does overwrite - complete overwrite everything? OR will it just overwrite files that exist with the same name, add new files if they exist and leave everything else alone? i'm thinking we want the 
second option. What if we have two potential flags (merge and delete)

merge (-m) will:
- overwrite files that exist with the same name
- add new files
- leave everything else in there alone so yes additional files could end up in the repo

delete (-d) will:
Completely delete the existing template repo and repopulate it.

you can't use both, just one or the other. 

@jlpalomino do you have any thoughts on this? this is for creating the template repo with the assignment files in it. 

i also realized that we need to be able to specify files that might go in each repo

so we may need an extra-files dir that has things like an image for the header and such. @kcranston this just occurred to me. if we want to add a header image to each repo we'd want the code to grab all files from that extra-files directory. the code will need to know where that is.

**Comment by kcranston** [comment]
-f force and -m merge makes sense to me (git-like, since we are doing git things). 

I've got a [sample config](https://github.com/kcranston/abc-classroom/blob/new-assignment/sample_config.yml) on a branch in my fork that has 1) extra_files with the contents in the yaml and 2) template_patterns, which specify the pattern matching for files in the nbgrader release dir you want to copy. The header images would be in the release dir. 

Is there another category of files - those that we can't include in the yaml (too big, binary, etc) and that are not in the nbgrader release dir?

**Comment by lwasser** [comment]
any files that are too big for git i presume would be data files. is that what you are talking about @kcranston or do you have another use case in mind? for any other data that students need we use `earthpy.io.get_data()` but please let me know if there is a use case i'm not considering.

i think we want the user to be able to add different types of files and not constrain the format of the files just in case -- we use .png and they use jpg, etc. i'm not sure if we need to consider how big the directory is to protect users from doing not good things (like putting large data on github) :)

**Comment by kcranston** [comment]
Oh, sorry - I meant "to big to list the contents directly in the config file" like this:

```
extra_files:
  gitignore:
  - .ipynb_checkpoints
  - .DS_Store
  README.md:
  - \nThis repository contains the notebooks for this week's assignment.
  - Complete the homework in each .ipynb notebook, commit your work, and
  - push the changes to github. Your instructor will pull the completed
  - assignment after the deadline.
  - \nOnce grading is complete, your instructor will push the results to a
  - file called `feedback.html`. You will need to pull the changes to your
  - local copy and open this file in a browser to view (github will not
  - render html files).

```

**Comment by lwasser** [comment]
ooooh you mean like text contents for the readme?

I could see a few options.
1. there is a txt file specified for the readme contents. that would make the markdown parsing potentially easier. maybe? 
2. we just allow them the option of creating their own readme file which would require a path to the file.

Let's chat more about this this am! i was thinking the initial take would keep things simple. we just generate a generic readme and what you have above seems reasonable for adding text to it.

**Comment by lwasser** [comment]
can we close this now with #91  merged @kcranston  ?
