### ISSUE TITLE
Add contributing file to the docs

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#83]
@nkorinek this is a small task that you can implement as well. 

Essentially look how we did it in earthpy.

https://github.com/earthlab/earthpy/blob/master/docs/contributing.rst

1. create a contributing.rst file
2. add that include text that you see in earthpy
3. add it to the index

then it should render in our docs and you are golden!
THANK YOU so much for helping me setup all of this documentation and infrastructure.

**Comment by nkorinek** [comment]
Addressed here: https://github.com/earthlab/abc-classroom/pull/84

**Comment by lwasser** [comment]
merged!! closing this!!
