### ISSUE TITLE
Inclusion of plt.show() in an autograded cell results in an extra empty plot

### ISSUE THREAD

**Issue by jlpalomino** [earthlab/abc-classroom#89]
Inclusion of `plt.show()` in an autograded cell results in an extra empty plot rendering underneath the actual plot created by the code cell.  We need to determine both the cause and potential fix, as it is unknown whether the issue is coming from matplotcheck, the notebook, etc. 

For now, we have asked students to comment out the code line for `plt.show()` in their autograded code cells.

This issue was originally opened in the auto-grading repo: https://github.com/earthlab/autograding-notebooks/issues/16

**Comment by lwasser** [comment]
ok! i am closing this as this is a matplotcheck thing but it's not avoidable. we just need to comment out `plt.show()`
