### ISSUE TITLE
Develop quickstart CLI tool that creates default directory structure

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#90]
Thinking about our discussion of paths in the config file, it might make things easier to have a quick-setup script that creates the default directory structure (maybe in the $HOME directory?) and puts these defaults into the config. They would still have to move the nbgrader dir and the student roster into place, but this would be less stuff to modify in the config and less worrying about paths. 

```
course_dir/
   config.yml
   cloned_repos/
   template_repos/
```
A instructor that wanted to use a different structure could edit paths in the config (or create symbolic links).

**Comment by lwasser** [comment]
this would be a great task for @nkorinek  to work on!! i agree. i'll task him with that.

**Comment by kcranston** [comment]
Let's talk about name for this and potential integration with abc-init. Current name is `dir-setup`.  Not sure the `dir` is necessary. What about `abc-quickstart` or just `abc-setup`? 

What do folks think about combining this with `abc-init` (which sets up the github integration) as part of the quickstart / setup? Then a user only has to run one command to get going. Would be good to keep `abc-init` separately callable for a user that wants to set things up manually instead of running the quickstart. (Aside - should we rename `abc-init` to `abc-github`?)

**Comment by lwasser** [comment]
i like abc-quickstart a lot @kcranston . i don't like that there is dir_setup and dirsetup in the module. it's a recipe for confusion!
(similar note - abc-classroom vs abcclassroom was really difficult to parse out with the package setup)

i'm not sure about combining abc-init. to me that is very different. it's the token setup for github and it only happens once even with many different classes. yet i could see someone using quickstart for a few classes. i'd like to keep them separate for now! 

@nkorinek what about renaming dirsetup to quickstart? 
@kcranston did you want the module to be renamed too? we struggled with what to call it!!

**Comment by lwasser** [comment]
just a note that @nkorinek is working on this #92

**Comment by nkorinek** [comment]
Merged in https://github.com/earthlab/abc-classroom/pull/110 can be closed @lwasser

**Comment by lwasser** [comment]
yay! closing! thanks @nkorinek !!
