### ISSUE TITLE
required version of python / support for python3.5

### ISSUE THREAD

**Issue by kcranston** [earthlab/abc-classroom#96]
What version of python should we require for abc-classroom? I ask for two reasons:

* [black](https://github.com/psf/black) requires python>=3.6
* my tests are failing on python3.5 because of low-level differences in pathlib, see [this pytest issue](https://github.com/pytest-dev/pytest/issues/5017)

I can alter the tests so that they pass on 3.5, but if black requires >3.5...

Thoughts?

**Comment by lwasser** [comment]
ayyyyyy hmmm gosh i hadn't thought about this carefully as it hasn't come up in our other packages!! i could ask around on twitter to see what people are doing... but i'm also open to just requiring 3.6 ?? we only run black in ci on 3.7!! maybe you can explain a bit more when we chat tomorrow the pros and cons?

**Comment by lwasser** [comment]
ok i've pinged the twitterverse and am completely sold. let's deprecate python 3.5 testing and just support 3.6+ !!  i can update travis today as i'd like to add a bit more to our docs as well. sound good @kcranston PR to come soon...

**Comment by lwasser** [comment]
@kcranston i just removed 3.5 from our travis build!! yay for faster CI. i'll close this but if you want to re-open it please do so!!
