### ISSUE TITLE
Add Changelog to abc-classroom

### ISSUE THREAD

**Issue by lwasser** [earthlab/abc-classroom#97]
Currently we don't have a good way to track updates and versions. 

- [x] add a changelog following earthpy and matplotcheck to do this!! 
- [ ] update the contributing file to document protocol!!  @nkorinek will work on that!

**Comment by lwasser** [comment]
so related to this -- i'll ask @nkorinek to see if he can dig up some of the issues he closed with prs and let's lump them all into the 0.0.11 release.

**Comment by kcranston** [comment]
https://github.com/earthlab/abc-classroom/blob/master/CHANGELOG.md 

yay!

**Comment by lwasser** [comment]
thanks @kcranston i had left this open as i had asked @nkorinek above to update the change log with the functionality and associated issues that he was working on . so i ddi the first part - create the changelog but i wanted him to add some things to it next. gonna reopen and when he adds those updates i'll close it !!

**Comment by lwasser** [comment]
i just updated the top comment to make the steps more clear!

**Comment by lwasser** [comment]
@nkorinek filled this out via #92
